name: Deploy to Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar dependencias y construir el proyecto
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 3. Desplegar la carpeta dist a la rama `deploy`
      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: deploy
